/**:
  ros__parameters:
    frame_id: map
    lidar_ip: 192.168.158.98
    lidar_port: 6543
    listen_port: 6668
    output_custommsg: true
    output_imu: true
    output_pointcloud: true
    topic_custommsg: custommsg
    topic_imu: imu
    topic_pointcloud: pointcloud
    adapter: eth0



